### ISSUE TITLE
Strange behaviour when using option -s (Subdirectory to sync) for two different folders

### ISSUE THREAD

**Issue by teoincontatto** [vitalif/grive2#43]
I have folders A, B and C and only want to sync A and B invoking grive twice with different -s value:

grive -s A
grive -s B

The problem is that grive update .grive_state after first invocation and if a new file was created in B it just think it was delete on remote before second grive invocation since timestamp of update is newer than timestamp of the new file due to first invocation.

I workaround this behaviour using this approach:

mv .grive_state.A .grive_state
grive -s A
mv .grive_state .grive_state.A

mv .grive_state.B .grive_state
grive -s B
mv .grive_state .grive_state.B

I think this should be address by grive using some kind of nested update states for paths inside .grive_state file.

**Comment by vitalif** [comment]
The recent commit resolves this issue by implicitly turning "-f" option on when you're changing the ignore regexp or the selected subdir to sync (which is internally also converted to a regex).
This makes grive think "remote is always newer" on such transitions... which is not the proper fix because some local changes may be overwritten... but at least it won't trash everything not in the subdir previously selected.
The proper fix requires the local "index" feature.

**Comment by vitalif** [comment]
P.S: You can use ```--ignore '^(?!subdir1|subdir2)'``` regex to always sync two subdirs.
Also I think I'll add support for multiple -s options for such regexes to be generated internally.
